version: 2.1

orbs:
  orb-tools: circleci/orb-tools@volatile
  test:
    # ref: https://github.com/ganta/git-orb/blob/master/.circleci/config.yml
    # Workaround for passing a SSH key with orb-tools/local-test-build command
    # https://github.com/CircleCI-Public/orb-tools-orb/blob/330d11bb0cdef3c2f24cb4e2c595ca01e55bfd8c/src/%40orb.yml#L107-L134
    commands:
      local-test-build:
        parameters:
          path:
            type: string
        steps:
          - run: cp << parameters.path >> .config/config.yml
          - run: mkdir -pv $(dirname _config.yml)
          - run: circleci config pack .config > _config.yml
          - run: cat _config.yml
          - run: circleci config process _config.yml > config.yml
          - run:
              command: |
                # Cannot access "~/.ssh" from working directory.
                cp ~/.ssh/id_rsa ./id_rsa
                circleci local execute --checkout-key ./id_rsa -c config.yml | \
                  tee local_build_output.txt /dev/stderr | \
                  tail -n 1 | \
                  grep "Success"

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [test-commands-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: guitarrapc/git-shallow-clone
          requires:
            - orb-tools/pack
      - orb-tools/test-in-builds:
          attach-workspace: true
          orb-name: git-shallow-clone
          test-steps:
            - test/local-test-build:
                path: tests/basic_test.yml
          name: basic-shallow-clone
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: SSH_KEY
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: SSH_KEY
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
