version: 2.1
orbs:
  <orb-name>: guitarrapc/git-shallow-clone@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout
  integration-test-checkout_advanced:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced
  integration-test-checkout_advanced_fetchoptions:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: '--shallow-since "5 days ago"'
          fetch_options: '--shallow-since "5 days ago"'
  integration-test-checkout_advanced_notags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: "--depth 1"
          fetch_options: "--depth 1000 --no-tags"
          tag_fetch_options: "--no-tags"
      # should be no tags
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -ne 0 ]; then exit 1; fi
  integration-test-checkout_advanced_tags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: "--depth 1"
          fetch_options: "--depth 1000"
      # should be all tags in fetch depth
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -eq 0 ]; then exit 1; fi
  integration-test-checkout_alpine:
    docker:
      - image: circleci/redis:alpine3.13
    steps:
      - run: apk update && apk add openssh git # openssh is required
      - git-shallow-clone/checkout
  integration-test-checkout_depth:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          depth: 5
          fetch_depth: 10
  integration-test-checkout_fetchdepth:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          fetch_depth: 1
  integration-test-checkout_keyscan_bitbucket:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          keyscan_bitbucket: true
  integration-test-checkout_keyscan_github:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          keyscan_github: true
  integration-test-checkout_macos:
    macos:
      xcode: 13.0.0
    steps:
      - git-shallow-clone/checkout
  integration-test-checkout_notags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          fetch_depth: 1000
          no_tags: true
      # should be no tags
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -ne 0 ]; then exit 1; fi
  integration-test-checkout_path:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          path: src
  integration-test-checkout_tags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          fetch_depth: 1000
      # should be all tags in fetch depth
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -eq 0 ]; then exit 1; fi
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # your integration test jobs go here: essentially, run all your orb's
      # jobs and commands to ensure they behave as expected. or, run other
      # integration tests of your choosing
      # Run any integration tests defined within the `jobs` key.
      - integration-test-checkout:
          filters: *filters
      - integration-test-checkout_advanced:
          filters: *filters
      - integration-test-checkout_advanced_fetchoptions:
          filters: *filters
      - integration-test-checkout_advanced_notags:
          filters: *filters
      - integration-test-checkout_advanced_tags:
          filters: *filters
      - integration-test-checkout_alpine:
          filters: *filters
      - integration-test-checkout_depth:
          filters: *filters
      - integration-test-checkout_fetchdepth:
          filters: *filters
      - integration-test-checkout_keyscan_bitbucket:
          filters: *filters
      - integration-test-checkout_keyscan_github:
          filters: *filters
      # - integration-test-checkout_macos:
      #     filters: *filters
      - integration-test-checkout_notags:
          filters: *filters
      - integration-test-checkout_path:
          filters: *filters
      - integration-test-checkout_tags:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: guitarrapc/git-shallow-clone
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test-checkout
            - integration-test-checkout_advanced
            - integration-test-checkout_advanced_fetchoptions
            - integration-test-checkout_advanced_notags
            - integration-test-checkout_advanced_tags
            - integration-test-checkout_alpine
            - integration-test-checkout_depth
            - integration-test-checkout_fetchdepth
            - integration-test-checkout_keyscan_bitbucket
            - integration-test-checkout_keyscan_github
            #- integration-test-checkout_macos
            - integration-test-checkout_notags
            - integration-test-checkout_path
            - integration-test-checkout_tags
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
